In [1]:
from sklearn import datasets
from sklearn.cluster import KMeans
from sklearn.utils import shuffle
import numpy as np
import pandas as pd

In [2]:
iris=datasets.load_iris()
X=iris.data
Y=iris.target

#Shuffle of Data 
X, Y = shuffle(X, Y)

In [3]:
model=KMeans(n_clusters=3,init='k-means++',max_iter=10,n_init=1,random_state=3425)

In [4]:
#Training of the model
model.fit(X)

# This is what KMeans thought (Prediction)
Y_Pred=model.labels_

In [5]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(Y,Y_Pred)
print(cm)

from sklearn.metrics import accuracy_score

print(accuracy_score(Y,Y_Pred))

[[50  0  0]
 [ 0  3 47]
 [ 0 36 14]]
0.44666666666666666


In [6]:
#Defining EM Model
from sklearn.mixture import GaussianMixture
model2=GaussianMixture(n_components=3,random_state=3425)

#Training of the model
model2.fit(X)

GaussianMixture(n_components=3, random_state=3425)

In [7]:
#Predicting classes for our data
Y_predict2 = model2.predict(X)

#Accuracy of EM Model
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(Y,Y_predict2)
print(cm)

from sklearn.metrics import accuracy_score

print(accuracy_score(Y,Y_predict2))

[[50  0  0]
 [ 0  5 45]
 [ 0 50  0]]
0.36666666666666664
